from flask import Flask, request, jsonify
app = Flask(__name__)

# --- SYSTEM STATE ---
# 1. The Idempotency Key Store (In production, this is a Redis cache or Database table)
processed_webhooks = set()

# 2. Data Mapping (E-commerce ID -> ERP SKU)
ecommerce_to_erp_mapping = {
    "ECOMM-998877": "SRV-IND-01"
}

# 3. ERP Inventory
inventory = {
    "SRV-IND-01": {"stock": 100}
}

@app.route('/api/webhook/ecommerce-order', methods=['POST'])
def process_order():
    data = request.get_json()
    webhook_id = data.get('webhook_id') # A unique ID generated by Shopify for this specific event
    ecomm_product_id = data.get('product_id')
    quantity = data.get('quantity')
    print(f"\n[ERP] Received Webhook Event ID: {webhook_id}")

    # --- IDEMPOTENCY CHECK ---
    if webhook_id in processed_webhooks:
        print(f"[ERP] DUPLICATE DETECTED! Webhook {webhook_id} was already processed. Ignoring safely.")
        # We MUST return 200 OK so the external system stops retrying!
        return jsonify({"status": "Already processed"}), 200

    # --- DATA MAPPING ---
    erp_sku = ecommerce_to_erp_mapping.get(ecomm_product_id)
    if not erp_sku:
        print(f"[ERP] ERROR: Unmapped Product ID {ecomm_product_id}")
        return jsonify({"error": "Unknown Product ID"}), 400

    # --- BUSINESS LOGIC ---
    print(f"[ERP] Translating E-comm ID '{ecomm_product_id}' -> ERP SKU '{erp_sku}'")
    inventory[erp_sku]["stock"] -= quantity
    print(f"[ERP] Order Processed! New Stock for {erp_sku}: {inventory[erp_sku]['stock']}")

    # Mark webhook as processed
    processed_webhooks.add(webhook_id)

    return jsonify({"status": "Success", "remaining_stock": inventory[erp_sku]["stock"]}), 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5015)
