"""conciliate

Revision ID: f2b80504d006
Revises: 
Create Date: 2026-04-18 18:28:35.098899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b80504d006'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('required_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Draft', nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.CheckConstraint("status IN ('Draft', 'Confirmed', 'Shipped', 'Invoiced', 'Cancelled')", name='orders_status_check'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_number'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders', schema='public')
    # ### end Alembic commands ###
